source 'https://rubygems.org'
gem 'berkshelf'
gem 'chefspec'
gem 'foodcritic', '>= 10.2.1'
gem 'inspec', '>= 1.18.0'
gem 'kitchen-inspec'
gem 'kitchen-vagrant'
gem 'rake'
gem 'rspec'
gem 'rubocop', '>= 0.48.1'
gem 'stove'
gem 'test-kitchen'
